name: Generate Datas

on:
  schedule: # Executar a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Gerar a animação da cobra
      - name: Gerar animação da cobra
        uses: Platane/snk@master
        with:
          github_user_name: DevLeandroCarrijo
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publicar no branch 'output'
      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
